- name: Deploy code
  uses: garygrossgarten/github-action-ssh@release
  on:
    push:
      branches: [ "main" ]
  with:
    command: deploy
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    privateKey: ${{ secrets.SSH_KEY}}
